//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CollisionDetection
{
    [Serializable]
    public class GenerateTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "collision_detection_msgs/GenerateTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public string move_group;
        public Sensor.JointStateMsg[] states;

        public GenerateTrajectoryRequest()
        {
            this.move_group = "";
            this.states = new Sensor.JointStateMsg[0];
        }

        public GenerateTrajectoryRequest(string move_group, Sensor.JointStateMsg[] states)
        {
            this.move_group = move_group;
            this.states = states;
        }

        public static GenerateTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new GenerateTrajectoryRequest(deserializer);

        private GenerateTrajectoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.move_group);
            deserializer.Read(out this.states, Sensor.JointStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.move_group);
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "GenerateTrajectoryRequest: " +
            "\nmove_group: " + move_group.ToString() +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
