//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CollisionDetection
{
    [Serializable]
    public class GenerateTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "collision_detection_msgs/GenerateTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg start_state;
        public Sensor.JointStateMsg end_state;

        public GenerateTrajectoryRequest()
        {
            this.start_state = new Sensor.JointStateMsg();
            this.end_state = new Sensor.JointStateMsg();
        }

        public GenerateTrajectoryRequest(Sensor.JointStateMsg start_state, Sensor.JointStateMsg end_state)
        {
            this.start_state = start_state;
            this.end_state = end_state;
        }

        public static GenerateTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new GenerateTrajectoryRequest(deserializer);

        private GenerateTrajectoryRequest(MessageDeserializer deserializer)
        {
            this.start_state = Sensor.JointStateMsg.Deserialize(deserializer);
            this.end_state = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_state);
            serializer.Write(this.end_state);
        }

        public override string ToString()
        {
            return "GenerateTrajectoryRequest: " +
            "\nstart_state: " + start_state.ToString() +
            "\nend_state: " + end_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
