//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CollisionDetection
{
    [Serializable]
    public class GenerateTrajectoryResponse : Message
    {
        public const string k_RosMessageName = "collision_detection_msgs/GenerateTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public Trajectory.JointTrajectoryMsg res;

        public GenerateTrajectoryResponse()
        {
            this.res = new Trajectory.JointTrajectoryMsg();
        }

        public GenerateTrajectoryResponse(Trajectory.JointTrajectoryMsg res)
        {
            this.res = res;
        }

        public static GenerateTrajectoryResponse Deserialize(MessageDeserializer deserializer) => new GenerateTrajectoryResponse(deserializer);

        private GenerateTrajectoryResponse(MessageDeserializer deserializer)
        {
            this.res = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.res);
        }

        public override string ToString()
        {
            return "GenerateTrajectoryResponse: " +
            "\nres: " + res.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
